spring.application.name=StudentPortal

server.port=${PORT:8080}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

app.security.jwt-secret=${JWT_SECRET}
app.security.jwt-expiration-ms=86400000
