spring.application.name=StudentPortal

spring.liquibase.enabled=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

app.security.jwt-secret=${JWT_SECRET}
app.security.jwt-expiration-ms=86400000

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always